engines:
  rubocop:
    enabled: true
    channel: rubocop-0-76
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      concurrency: 1
    exclude_patterns:
      - /spec/**/*
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
  flog:
    enabled: true
    config:
      all: false
      threshold: 0.6
    exclude_patterns:
      - /spec/**/*
ratings:
   paths:
   - Gemfile.lock
   - "**.rb"
