# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-templates-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: rails-templates-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - cc-test-reporter

  test:
    docker:
      - image: circleci/ruby:2.6.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: rails-templates-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Install rails
          command: gem install rails

      - run:
          name: Create new rails app using the template
          command: |
            rails new ../rails-new-app --template=template.rb \
                                       --skip-action-mailer \
                                       --skip-action-mailbox \
                                       --skip-action-text \
                                       --skip-active-storage \
                                       --skip-action-cable \
                                       --skip-sprockets \
                                       --skip-spring \
                                       --skip-bootsnap \
                                       --skip-test \
                                       --no-rc \
                                       --api

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
