# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install rails
          command: gem install rails

      - run:
          name: Create new rails app using the template
          command: |
            rails new ../rails-new-app --template=template.rb \
                                       --skip-action-mailer \
                                       --skip-action-mailbox \
                                       --skip-action-text \
                                       --skip-active-storage \
                                       --skip-action-cable \
                                       --skip-sprockets \
                                       --skip-spring \
                                       --skip-bootsnap \
                                       --skip-test \
                                       --no-rc \
                                       --api

workflows:
  version: 2
  test:
    jobs:
      - test      
